ifdef CONFIG_CC_OPTIMIZE_FOR_PERF
CFLAGS_msm_ispif.o += -Wno-maybe-uninitialized
endif
ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
