obj-$(CONFIG_SLIMPORT_ANX7808)	+= slimport.o slimport_tx_drv.o slimport_tx_reg_init.o
obj-$(CONFIG_SLIMPORT_REGISTER_SET_TEST)	+= slimport_register_set_test.o
obj-$(CONFIG_SLIMPORT_ANX7805)	+= 7805/
